echo " "
echo "                   _______  _______  _______  _______  _______                  "
echo "                  |       ||       ||       ||       ||       |                 "
echo "                  |    ___||   _   ||  _____||___    ||____   |                 "
echo "                  |   |___ |  | |  || |_____  ___|   | ____|  |                 "
echo "                  |    ___||  |_|  ||_____  ||___    || ______|                 "
echo "                  |   |___ |       | _____| | ___|   || |_____                  "
echo "                  |_______||_______||_______||_______||_______|                 "
echo "                     Assisted Installation Script Collection                    "
echo " "
echo "Hello there! This script collection will guide you through the process of"
echo "installing a new copy of the EOS32 operating system (of course, it's the system "
echo "you're using RIGHT NOW!). Please follow the instructions and read all lines"
echo "marked with a double-hashtag (##) with the highest available amount of attention"
echo "Thank you and have fun!"
echo " "
echo "## Step 1.1: Compile the boot manager..."
cd /usr/src/bin/mkmboot; make
cd /usr/install
echo "## Step 1.2: Prepare a partition file for mkpart..."
echo "# generated by eos32-aisc" > disk.part
echo "/usr/src/bin/mkmboot/mbootblk" >> disk.part
echo "## Step 1.3: Get the current partition scheme from disk /dev/idedisk..."
shpart /dev/idedisk --readable-for-mkpart >> disk.part
echo "## Step 1.4: Please modify the partition file (disk.part) and write down the "
echo "  numbers for each partition to the next install file (install2.sh)."