#
# Makefile for building EOS32 file systems
#

BUILD = ../..

DSK_IMG = ../disk.img

all:		filesystems

filesystems:
		$(BUILD)/bin/EOS32-mkfs $(DSK_IMG) 1 root.fsys
		$(BUILD)/bin/EOS32-mkfs $(DSK_IMG) 3 usr.fsys
		$(BUILD)/bin/EOS32-mkfs $(DSK_IMG) 4 home.fsys

clean:
		rm -f *~
